###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/1

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Test 1",
    "email": "test1@test.com"
}

###
PATCH http://localhost:8080/api/users/1
Content-Type: application/json

{
    "name": "Name Updated"
}

###
DELETE http://localhost:8080/api/users/1
